Bottin/config/routes.rb
Rails.application.routes.draw do
  resources :works
  #resources :telephones
  resources :contacts do |c|
    resources :telephones
  end
  #get '/telephones/:contact_id/new', to: 'telephones#new'  , as: 'tele'
  get '/contacts/rapport/:year', to: 'contacts#rapport' # url qui pointe vers une fonction dans le controller de contact
  get '/contacts/newWork/:contact',to: 'contacts#newWork', as: 'newWork'


  root 'contacts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Bottin/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bottin/app/models/contact.rb
class Contact < ApplicationRecord
	validate :birthday_must_be_in_the_past
	validates_length_of :first_name, within: 2..20
	validates_length_of :last_name, within: 2..20
	has_many :telephones, dependent: :destroy
	has_many :contacts_works
	def fullname
		self.first_name + " " + self.last_name
	end

	def first_name
		self[:first_name] || ""
	end

	def last_name
		self[:last_name] || ""
	end

	def birthday_must_be_in_the_past
		if self.birthday.present? && self.birthday > Date.today
			errors.add(:birthday,"must be in the past")
		end
	end
end

Bottin/app/models/contacts_work.rb
class ContactsWork < ApplicationRecord
  belongs_to :contact
  belongs_to :work
  
end

Bottin/app/models/telephone.rb
class Telephone < ApplicationRecord
	belongs_to :contact
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
end

Bottin/app/models/work.rb
class Work < ApplicationRecord
  has_many :contacts_works
end

Bottin/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Bottin/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def rapport
  	@contacts = Contact.where("YEAR(birthday) = ?", params[:year])
  end
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show

  end
  def newWork
    @works = Work.all
  end
  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy

    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :birthday)
    end
end

Bottin/app/controllers/telephones_controller.rb
class TelephonesController < ApplicationController
  before_action :set_telephone, only: [:show, :edit, :update, :destroy]
  before_action :set_all_contacts, only: [:edit, :new, :update ,:create]
  # GET /telephones
  # GET /telephones.json
  def index
    @telephones = Telephone.all
  end

  # GET /telephones/1
  # GET /telephones/1.json
  def show
  end

  # GET /telephones/new
  def new
    @telephone = Telephone.new
    @telephone.contact = Contact.find(params[:contact_id])
  end

  # GET /telephones/1/edit
  def edit
  end

  # POST /telephones
  # POST /telephones.json
  def create
    @telephone = Telephone.new(telephone_params)

    respond_to do |format|
      if @telephone.save
        format.html { redirect_to @telephone.contact, notice: 'Telephone was successfully created.' }
        format.json { render :show, status: :created, location: @telephone }
      else
        format.html { render :new }
        format.json { render json: @telephone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /telephones/1
  # PATCH/PUT /telephones/1.json
  def update
    respond_to do |format|
      if @telephone.update(telephone_params)
        format.html { redirect_to @telephone.contact, notice: 'Telephone was successfully updated.' }
        format.json { render :show, status: :ok, location: @telephone }
      else
        format.html { render :edit }
        format.json { render json: @telephone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /telephones/1
  # DELETE /telephones/1.json
  def destroy
    @telephone.destroy
    respond_to do |format|
      format.html { redirect_to @telephone.contact, notice: 'Telephone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_telephone
      @telephone = Telephone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def telephone_params
      params.require(:telephone).permit(:phonenumber, :email, :contact_id)
    end
    def set_all_contacts
      @contacts = Contact.all
    end
end

Bottin/app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:name)
    end
end

Bottin/app/helpers/application_helper.rb
module ApplicationHelper
end

Bottin/app/helpers/contacts_helper.rb
module ContactsHelper
end

Bottin/app/helpers/telephones_helper.rb
module TelephonesHelper
end

Bottin/app/helpers/works_helper.rb
module WorksHelper
end

Bottin/app/views/contacts/_form.html.erb
<%= form_for(contact) do |f| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :birthday %>
    <%= f.date_select :birthday, start_year: Date.today.year - 20, end_year: Date.today.year - 1 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Bottin/app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

Bottin/app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.birthday %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

Bottin/app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

Bottin/app/views/contacts/newWork.html.erb
@works

Bottin/app/views/contacts/rapport.html.erb
<tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.birthday.year %></td>
      </tr>
  <% end %>

Bottin/app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @contact.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.last_name %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @contact.birthday %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

<hr />

<table>
  <thead>
    <tr>
      <th>Phonenumber</th>
      <th>Email</th>
      <th colspan="3"><%= link_to 'ajouter telephone a ' + @contact.fullname, new_contact_telephone_path(@contact) %></th>
    </tr>
  </thead>

  <tbody>
    <% @contact.telephones.each do |telephone| %>
      <tr>
        <td><%= telephone.phonenumber %></td>
        <td><%= telephone.email %></td>
        <td><%= link_to 'Show', contact_telephone_path(@contact,telephone) %></td>
        <td><%= link_to 'Edit', edit_contact_telephone_path(@contact,telephone) %></td>
        <td><%= link_to 'Destroy', contact_telephone_path(@contact,telephone), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr />

<table>
  <thead>
    <tr>
      <th>name</th>
      <th colspan="3"><%= link_to 'ajouter travail a ' + @contact.fullname, newWork_path(@contact) %></th>
    </tr>
  </thead>

  <tbody>
    <%  @contact.contacts_works do |work|  %>
      <tr>
        <td><%= works.w %></td>
        <td><%#= telephone.email %></td>
        <td><%#= link_to 'Show', contact_telephone_path(@contact) %></td>
        <td><%#= link_to 'Edit', edit_contact_telephone_path(@contact) %></td>
        <td><%#= link_to 'Destroy', contact_telephone_path(@contact,telephone), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

Bottin/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bottin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Bottin/app/views/telephones/_form.html.erb
<h1><%= telephone.contact.fullname %></h1>

<%= form_for(telephone,{:url => [telephone.contact,telephone]}) do |f| %>
  <%= f.hidden_field :contact_id %>

  <% if telephone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(telephone.errors.count, "error") %> prohibited this telephone from being saved:</h2>

      <ul>
      <% telephone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phonenumber %>
    <%= f.text_field :phonenumber %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Bottin/app/views/telephones/edit.html.erb
<h1>Editing Telephone</h1>

<%= render 'form', telephone: @telephone %>

<%= link_to 'Show', contact_telephone_path(@telephone) %> |
<%= link_to 'Back', @telephone.contact %>

Bottin/app/views/telephones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Telephones</h1>

<table>
  <thead>
    <tr>
      <th>Phonenumber</th>
      <th>Email</th>
      <th>Contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @telephones.each do |telephone| %>
      <tr>
        <td><%= telephone.phonenumber %></td>
        <td><%= telephone.email %></td>
        <td><%= telephone.contact.nil? ? "no name" : telephone.contact.fullname%></td>
        <td><%= link_to 'Show', telephone %></td>
        <td><%= link_to 'Edit', edit_telephone_path(telephone) %></td>
        <td><%= link_to 'Destroy', telephone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Telephone', new_telephone_path %>

Bottin/app/views/telephones/new.html.erb
<h1>New Telephone</h1>

<%= render 'form', telephone: @telephone %>

<%= link_to 'Back', contact_path(@telephone.contact) %>

Bottin/app/views/telephones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phonenumber:</strong>
  <%= @telephone.phonenumber %>
</p>

<p>
  <strong>Email:</strong>
  <%= @telephone.email %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @telephone.contact.fullname %>
</p>

<%= link_to 'Edit', edit_contact_telephone_path(@telephone) %> |
<%= link_to 'Back', @telephone.contact %>

Bottin/app/views/works/_form.html.erb
<%= form_for(work) do |f| %>
  <% if work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Bottin/app/views/works/edit.html.erb
<h1>Editing Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

Bottin/app/views/works/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Works</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= work.name %></td>
        <td><%= link_to 'Show', work %></td>
        <td><%= link_to 'Edit', edit_work_path(work) %></td>
        <td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work', new_work_path %>

Bottin/app/views/works/new.html.erb
<h1>New Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Back', works_path %>

Bottin/app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @work.name %>
</p>

<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>